### PR TITLE
OCM-2460: Added update/remove taints from machine pool

### PR DESCRIPTION
**Pull request by sagidayan**

### CODE REVIEW

**Comment by sagidayan** [comment]
Found an issue, holding until its fixed.

**Comment by sagidayan** [comment]
/unhold

> Found an issue, holding until its fixed.

False positive. There was no issue with the PR, But with the environment @tshefi tested on. This PR should be fine, and tested locally by me with @tshefi 's cluster , In addition to subsystem tests.

**Comment by tshefi** [comment]
Looking good, tested and working as expected.

**Pull request merged**
